/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://g437zb4bizgtbkygedqgrnnzwa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bf7h2xm34bdezcsssu4g7h74na",
    "aws_cognito_identity_pool_id": "us-east-1:f96d5c90-ec4b-4c6f-806d-1fe4974719b4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5zbpzMQA2",
    "aws_user_pools_web_client_id": "56sqns0hoe9kqm7m2ckdgr4fdv",
    "oauth": {}
};


export default awsmobile;
